image: docker.elastic.co/beats/filebeat-oss

daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: "secops-cluster:9200"
        index: "logstash-beta--%{+yyyy.MM.dd}"
        username: "admin"
        password: "admin"
      setup.ilm.enabled: false
      setup.template.name: "filebeat"
      setup.template.pattern: "filebeat-oss-*"
