apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: opensearch
  labels:
    k8s-app: filebeat
---
apiVersion: authorization.k8s.io
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: authorization.k8s.io
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: opensearch
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: authorization.k8s.io
