apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: opensearch
  labels:
    k8s-app: filebeat
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: ["autoscaling"] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
