apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: opensearch
  labels:
    k8s-app: filebeat
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:|^\s*$'
      multiline.negate: false
      multiline.match: after
      processors:
        - add_kubernetes_metadata:
            in_cluster: true    
