kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  namespace: opensearch
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  type: LoadBalancer
